name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e320aee3fc28a94cb9961ae37816098a8541eea9660ae7cdc411feb83de7179"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
