name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b36ce3595437265b7cda7fcbec6b8db15929506f62c9f4093c2daa6631892611"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
