name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4ddf359d4c99c209bb7b91e2f53d33a56316e3bb42e62e316ebc4d2cecdf49"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
