name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a8551036d3fd9a4fa631c6a35c15fcb59d4ed342243b5e32babff43dbb6491"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
