name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b941de6eb2eda52d80dc846f74da877bd5d5c6312ecb4605c87b63ba32e7f9c3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
