name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d5e632c1859234d6501552ec1259fc49df51227952f8351eac8fa65a0482b07"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
