name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7b69333086ba1ea3600fa8c831b88f4233c0f1e394d6e0437792a3f86a342b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
