name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d2ffe7d81431cbc0cc6f0e1eb3329e0ade43a516a55c24e06fe01f7594f2be6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
