name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3da66a06ff66ab0d5606056663906fd78a2d8870952a11cb9ddc77e2a965c237"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
