name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4c13b33a59f3ac30f008f7ffb1d61bdec3d16198a1ec9aac43b852b902e9d89"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
